import type { StoreSettings } from "@/lib/storeTheme";

export type ThemePresetPatch = Partial<
  Pick<
    StoreSettings,
    | "theme"
    | "primary_color"
    | "secondary_color"
    | "accent_color"
    | "background_color"
    | "font_family"
    | "button_style"
    | "border_radius"
    | "hero_layout"
  >
>;

export type LayoutTemplate =
  | "editorial"
  | "grid-dense"
  | "magazine"
  | "showcase"
  | "storytelling"
  | "catalog";

export interface ThemePreset {
  id: string;
  name: string;
  brandName: string;
  tagline: string;
  description: string;
  niche: string;
  accent: string;
  highlights: string[];
  layout: LayoutTemplate;
  patch: ThemePresetPatch;
  heroHeading: string;
  heroSubheading: string;
  heroCta: string;
}

export const THEME_PRESETS: ThemePreset[] = [
  // 1. Fashion / Streetwear
  {
    id: "streetwear",
    name: "Streetwear",
    brandName: "VXNDR",
    tagline: "Dark · Bold · Modern",
    description: "Urban streetwear with bold typography and dark aesthetics.",
    niche: "Fashion / Streetwear",
    accent: "from-zinc-800 via-zinc-900 to-black",
    highlights: ["Dark canvas", "Bold type", "Urban feel"],
    layout: "showcase",
    patch: {
      theme: "bold",
      primary_color: "#ef4444",
      secondary_color: "#fafafa",
      accent_color: "#facc15",
      background_color: "#0a0a0a",
      font_family: "Bebas",
      button_style: "square",
      border_radius: "small",
      hero_layout: "fullbleed",
    },
    heroHeading: "DROP 07 — OUT NOW",
    heroSubheading: "Limited edition streetwear. Raw. Unapologetic. Yours.",
    heroCta: "Shop the Drop",
  },
  // 2. Luxury Fashion
  {
    id: "luxe",
    name: "Luxe",
    brandName: "Maison Élan",
    tagline: "Clean · White · Elegant",
    description: "Refined elegance with serif headings and generous whitespace.",
    niche: "Luxury Fashion",
    accent: "from-stone-100 via-white to-stone-50",
    highlights: ["White canvas", "Serif type", "Editorial"],
    layout: "editorial",
    patch: {
      theme: "minimal",
      primary_color: "#1a1a1a",
      secondary_color: "#1a1a1a",
      accent_color: "#9a8c7c",
      background_color: "#faf9f7",
      font_family: "Cormorant",
      button_style: "square",
      border_radius: "none",
      hero_layout: "split",
    },
    heroHeading: "Autumn/Winter Collection",
    heroSubheading: "Timeless pieces crafted from the finest materials.",
    heroCta: "View Collection",
  },
  // 3. Tech Gadgets
  {
    id: "techflow",
    name: "TechFlow",
    brandName: "NovaTech",
    tagline: "Futuristic · Gradients · Neon",
    description: "Cutting-edge tech store with neon accents and dark UI.",
    niche: "Tech Gadgets",
    accent: "from-cyan-500 via-blue-600 to-purple-700",
    highlights: ["Neon accents", "Dark UI", "Futuristic"],
    layout: "grid-dense",
    patch: {
      theme: "bold",
      primary_color: "#06b6d4",
      secondary_color: "#e2e8f0",
      accent_color: "#a855f7",
      background_color: "#0c0c14",
      font_family: "Space Grotesk",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "fullbleed",
    },
    heroHeading: "Next-Gen Tech",
    heroSubheading: "Discover the future of consumer electronics.",
    heroCta: "Explore Gear",
  },
  // 4. Minimalist Home Decor
  {
    id: "habitat",
    name: "Habitat",
    brandName: "HAUS",
    tagline: "Soft · Clean · Whitespace",
    description: "Calm, minimal home décor with soft earth tones.",
    niche: "Home Decor",
    accent: "from-amber-50 via-orange-50 to-yellow-50",
    highlights: ["Soft palette", "Clean layout", "Warm tones"],
    layout: "editorial",
    patch: {
      theme: "minimal",
      primary_color: "#92400e",
      secondary_color: "#1c1917",
      accent_color: "#d97706",
      background_color: "#fffbf5",
      font_family: "Outfit",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "centered",
    },
    heroHeading: "Design Your Space",
    heroSubheading: "Thoughtfully curated pieces for mindful living.",
    heroCta: "Shop Home",
  },
  // 5. Beauty & Cosmetics
  {
    id: "bloom",
    name: "Bloom",
    brandName: "Pétale",
    tagline: "Pastel · Smooth · Feminine",
    description: "Soft pastels and smooth curves for beauty brands.",
    niche: "Beauty & Cosmetics",
    accent: "from-pink-200 via-rose-100 to-fuchsia-100",
    highlights: ["Pastel colors", "Smooth UI", "Rounded"],
    layout: "magazine",
    patch: {
      theme: "modern",
      primary_color: "#db2777",
      secondary_color: "#1e1b4b",
      accent_color: "#f472b6",
      background_color: "#fdf2f8",
      font_family: "Jakarta",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "split",
    },
    heroHeading: "Glow Naturally",
    heroSubheading: "Clean beauty essentials for your daily ritual.",
    heroCta: "Shop Beauty",
  },
  // 6. Fitness & Gym
  {
    id: "ironclad",
    name: "IronClad",
    brandName: "FORGE",
    tagline: "Strong · Energetic · Bold",
    description: "High-energy fitness store with powerful visuals.",
    niche: "Fitness & Gym",
    accent: "from-orange-500 via-red-500 to-rose-600",
    highlights: ["Bold colors", "Energetic", "Dynamic"],
    layout: "showcase",
    patch: {
      theme: "bold",
      primary_color: "#ea580c",
      secondary_color: "#fafafa",
      accent_color: "#16a34a",
      background_color: "#0f0f0f",
      font_family: "Archivo",
      button_style: "square",
      border_radius: "small",
      hero_layout: "fullbleed",
    },
    heroHeading: "TRAIN HARDER",
    heroSubheading: "Premium fitness gear engineered for performance.",
    heroCta: "Shop Now",
  },
  // 7. Sneakers
  {
    id: "kickz",
    name: "Kickz",
    brandName: "STEPUP",
    tagline: "Urban · Bold · Product Cards",
    description: "Bold sneaker store with oversized product cards.",
    niche: "Sneakers",
    accent: "from-violet-600 via-purple-600 to-indigo-700",
    highlights: ["Big cards", "Urban", "Bold type"],
    layout: "showcase",
    patch: {
      theme: "modern",
      primary_color: "#7c3aed",
      secondary_color: "#f8fafc",
      accent_color: "#f59e0b",
      background_color: "#111111",
      font_family: "Syne",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "split",
    },
    heroHeading: "Fresh Kicks",
    heroSubheading: "Exclusive drops you won't find anywhere else.",
    heroCta: "Shop Sneakers",
  },
  // 8. Jewelry
  {
    id: "aurum",
    name: "Aurum",
    brandName: "Éclat",
    tagline: "Premium · Gold Accents · Elegant",
    description: "Luxurious jewelry store with gold and dark accents.",
    niche: "Jewelry",
    accent: "from-amber-300 via-yellow-200 to-orange-200",
    highlights: ["Gold accents", "Premium feel", "Serif type"],
    layout: "editorial",
    patch: {
      theme: "bold",
      primary_color: "#b8860b",
      secondary_color: "#fef3c7",
      accent_color: "#d4af37",
      background_color: "#0d0b08",
      font_family: "Playfair",
      button_style: "square",
      border_radius: "none",
      hero_layout: "centered",
    },
    heroHeading: "Timeless Elegance",
    heroSubheading: "Handcrafted jewelry for life's finest moments.",
    heroCta: "Discover",
  },
  // 9. Kids Toys
  {
    id: "playtime",
    name: "Playtime",
    brandName: "ToyBox",
    tagline: "Colorful · Playful · Fun",
    description: "Bright, playful toy store with rounded shapes.",
    niche: "Kids Toys",
    accent: "from-yellow-300 via-green-300 to-blue-300",
    highlights: ["Colorful", "Playful shapes", "Fun UI"],
    layout: "grid-dense",
    patch: {
      theme: "modern",
      primary_color: "#2563eb",
      secondary_color: "#1e293b",
      accent_color: "#f59e0b",
      background_color: "#fffdf7",
      font_family: "Bricolage",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "split",
    },
    heroHeading: "Play. Learn. Grow.",
    heroSubheading: "Toys that spark imagination and creativity.",
    heroCta: "Shop Toys",
  },
  // 10. Pet Store
  {
    id: "pawpal",
    name: "PawPal",
    brandName: "Furry & Co",
    tagline: "Friendly · Warm · Organic",
    description: "Warm, friendly pet store with organic shapes.",
    niche: "Pet Store",
    accent: "from-orange-200 via-amber-100 to-yellow-100",
    highlights: ["Warm colors", "Friendly", "Rounded"],
    layout: "magazine",
    patch: {
      theme: "modern",
      primary_color: "#c2410c",
      secondary_color: "#1c1917",
      accent_color: "#65a30d",
      background_color: "#fefce8",
      font_family: "Outfit",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "split",
    },
    heroHeading: "Happy Pets, Happy Life",
    heroSubheading: "Premium supplies for your furry best friends.",
    heroCta: "Shop Now",
  },
  // 11. Electronics Marketplace
  {
    id: "circuitry",
    name: "Circuitry",
    brandName: "ByteShop",
    tagline: "Structured · Grid · Clean",
    description: "Structured electronics marketplace with dense product grids.",
    niche: "Electronics",
    accent: "from-blue-100 via-slate-100 to-gray-100",
    highlights: ["Dense grid", "Clean", "Structured"],
    layout: "catalog",
    patch: {
      theme: "grid",
      primary_color: "#2563eb",
      secondary_color: "#0f172a",
      accent_color: "#dc2626",
      background_color: "#f8fafc",
      font_family: "Inter",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "centered",
    },
    heroHeading: "Best Deals on Electronics",
    heroSubheading: "Thousands of products at unbeatable prices.",
    heroCta: "Browse Deals",
  },
  // 12. Handmade Crafts
  {
    id: "artisan",
    name: "Artisan",
    brandName: "Threadwork",
    tagline: "Organic · Textured · Warm",
    description: "Handmade crafts store with organic, textured aesthetic.",
    niche: "Handmade Crafts",
    accent: "from-stone-300 via-amber-100 to-orange-100",
    highlights: ["Organic feel", "Textured", "Warm tones"],
    layout: "storytelling",
    patch: {
      theme: "minimal",
      primary_color: "#78350f",
      secondary_color: "#292524",
      accent_color: "#b45309",
      background_color: "#faf5ef",
      font_family: "Fraunces",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "split",
    },
    heroHeading: "Made with Love",
    heroSubheading: "Unique handcrafted pieces by independent artisans.",
    heroCta: "Explore Crafts",
  },
  // 13. Furniture
  {
    id: "interior",
    name: "Interior",
    brandName: "MOBLER",
    tagline: "Large Images · Editorial · Modern",
    description: "Furniture store with editorial layouts and large imagery.",
    niche: "Furniture",
    accent: "from-neutral-200 via-stone-100 to-zinc-100",
    highlights: ["Large images", "Editorial", "Spacious"],
    layout: "editorial",
    patch: {
      theme: "minimal",
      primary_color: "#18181b",
      secondary_color: "#18181b",
      accent_color: "#a3a3a3",
      background_color: "#ffffff",
      font_family: "Manrope",
      button_style: "square",
      border_radius: "small",
      hero_layout: "fullbleed",
    },
    heroHeading: "Live Beautifully",
    heroSubheading: "Scandinavian-inspired furniture for modern spaces.",
    heroCta: "Shop Furniture",
  },
  // 14. Coffee Brand
  {
    id: "brewhaus",
    name: "BrewHaus",
    brandName: "Roast & Co",
    tagline: "Warm · Storytelling · Rich",
    description: "Warm coffee brand with storytelling layout.",
    niche: "Coffee",
    accent: "from-amber-700 via-orange-600 to-yellow-600",
    highlights: ["Warm tones", "Story-driven", "Rich feel"],
    layout: "storytelling",
    patch: {
      theme: "modern",
      primary_color: "#92400e",
      secondary_color: "#fefce8",
      accent_color: "#ca8a04",
      background_color: "#1c1210",
      font_family: "DM Serif",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "fullbleed",
    },
    heroHeading: "Crafted with Passion",
    heroSubheading: "Single-origin beans roasted to perfection.",
    heroCta: "Shop Coffee",
  },
  // 15. Organic Food
  {
    id: "greens",
    name: "Greens",
    brandName: "FreshLeaf",
    tagline: "Green · Fresh · Organic",
    description: "Fresh organic food store with green aesthetic.",
    niche: "Organic Food",
    accent: "from-green-200 via-emerald-100 to-lime-100",
    highlights: ["Green palette", "Fresh", "Natural"],
    layout: "magazine",
    patch: {
      theme: "modern",
      primary_color: "#15803d",
      secondary_color: "#14532d",
      accent_color: "#84cc16",
      background_color: "#f0fdf4",
      font_family: "Outfit",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "split",
    },
    heroHeading: "Eat Fresh, Live Well",
    heroSubheading: "Organic produce delivered straight to your door.",
    heroCta: "Shop Fresh",
  },
  // 16. Digital Products
  {
    id: "pixelcraft",
    name: "PixelCraft",
    brandName: "Stackly",
    tagline: "Modern · SaaS · Clean",
    description: "Modern digital products store with SaaS-style design.",
    niche: "Digital Products",
    accent: "from-indigo-500 via-blue-500 to-cyan-500",
    highlights: ["SaaS style", "Clean grid", "Modern"],
    layout: "grid-dense",
    patch: {
      theme: "modern",
      primary_color: "#4f46e5",
      secondary_color: "#0f172a",
      accent_color: "#06b6d4",
      background_color: "#ffffff",
      font_family: "Sora",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "centered",
    },
    heroHeading: "Digital Tools That Work",
    heroSubheading: "Templates, kits, and resources for creators.",
    heroCta: "Browse Products",
  },
  // 17. Gaming Store
  {
    id: "gameforge",
    name: "GameForge",
    brandName: "NEXUS",
    tagline: "Dark · Neon · Gaming",
    description: "Dark gaming store with neon accents and bold type.",
    niche: "Gaming",
    accent: "from-green-500 via-emerald-500 to-teal-600",
    highlights: ["Dark UI", "Neon green", "Bold"],
    layout: "showcase",
    patch: {
      theme: "bold",
      primary_color: "#10b981",
      secondary_color: "#f0fdf4",
      accent_color: "#8b5cf6",
      background_color: "#070b0e",
      font_family: "Space Grotesk",
      button_style: "square",
      border_radius: "small",
      hero_layout: "fullbleed",
    },
    heroHeading: "LEVEL UP YOUR GAME",
    heroSubheading: "Pro gaming gear for competitive players.",
    heroCta: "Shop Gaming",
  },
  // 18. Sports Equipment
  {
    id: "athlete",
    name: "Athlete",
    brandName: "ProEdge",
    tagline: "Clean · Dynamic · Active",
    description: "Clean sports equipment store with dynamic layout.",
    niche: "Sports Equipment",
    accent: "from-blue-500 via-sky-400 to-cyan-400",
    highlights: ["Clean layout", "Dynamic", "Active"],
    layout: "catalog",
    patch: {
      theme: "grid",
      primary_color: "#0284c7",
      secondary_color: "#0f172a",
      accent_color: "#f97316",
      background_color: "#f0f9ff",
      font_family: "Manrope",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "split",
    },
    heroHeading: "Gear Up for Greatness",
    heroSubheading: "Professional sports equipment for every athlete.",
    heroCta: "Shop Sports",
  },
  // 19. Watch Store
  {
    id: "chronos",
    name: "Chronos",
    brandName: "MERIDIAN",
    tagline: "Luxury · Minimal · B&W",
    description: "Luxury watch store with minimal black and white design.",
    niche: "Watches",
    accent: "from-zinc-300 via-neutral-200 to-stone-200",
    highlights: ["B&W palette", "Luxury minimal", "Serif"],
    layout: "editorial",
    patch: {
      theme: "minimal",
      primary_color: "#171717",
      secondary_color: "#171717",
      accent_color: "#a3a3a3",
      background_color: "#fafafa",
      font_family: "Playfair",
      button_style: "square",
      border_radius: "none",
      hero_layout: "centered",
    },
    heroHeading: "Time, Elevated",
    heroSubheading: "Swiss precision meets contemporary design.",
    heroCta: "View Timepieces",
  },
  // 20. General Dropshipping
  {
    id: "trendmart",
    name: "TrendMart",
    brandName: "TrendMart",
    tagline: "Conversion · Clean · Versatile",
    description: "Conversion-focused general store with clean design.",
    niche: "General / Dropshipping",
    accent: "from-violet-400 via-fuchsia-400 to-pink-400",
    highlights: ["CRO-focused", "Badges", "Trust signals"],
    layout: "catalog",
    patch: {
      theme: "modern",
      primary_color: "#7c3aed",
      secondary_color: "#0f172a",
      accent_color: "#f59e0b",
      background_color: "#ffffff",
      font_family: "Jakarta",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "centered",
    },
    heroHeading: "Trending Now",
    heroSubheading: "Top-rated products with free shipping worldwide.",
    heroCta: "Shop Trending",
  },
];

export function applyPreset(
  current: StoreSettings,
  preset: ThemePreset,
): StoreSettings {
  return { ...current, ...preset.patch };
}

export function getPresetById(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((p) => p.id === id);
}
