[functions.create-chargily-checkout]
verify_jwt = true

[functions.chargily-webhook]
verify_jwt = false

[functions.activate-plan]
verify_jwt = true

[functions.activate-credits]
verify_jwt = true

[functions.get-bordereau]
verify_jwt = true

[functions.send-email]
verify_jwt = false
