export const THEME_PRESETS = [
  {
    id: "sahara",
    name: "Sahara Gold",
    description:
      "Desert-inspired warmth with gold accents on deep earth tones. Luxury jewelry, leather goods.",
    preview: { bg: "#0f0d0a", primary: "#D4A853", accent: "#8B6914", font: "Playfair Display" },
    settings: {
      theme: "sahara",
      primary_color: "#D4A853",
      secondary_color: "#1a1410",
      accent_color: "#8B6914",
      background_color: "#0f0d0a",
      font_family: "Playfair Display",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "fullbleed",
      hero_heading: "Discover the Beauty of the Sahara",
      hero_subheading: "Handcrafted treasures from the heart of Algeria.",
      hero_cta_label: "Explore Collection",
    },
    navbar: "classic" as const,
    footer: "branded" as const,
    sectionPresets: [],
  },
  {
    id: "mediterranean",
    name: "Mediterranean Breeze",
    description:
      "Cool blues and whites inspired by the Algerian coast. Fashion, home decor, lifestyle.",
    preview: { bg: "#f0f7ff", primary: "#2563EB", accent: "#0ea5e9", font: "Outfit" },
    settings: {
      theme: "mediterranean",
      primary_color: "#2563EB",
      secondary_color: "#1e3a5f",
      accent_color: "#0ea5e9",
      background_color: "#f0f7ff",
      font_family: "Outfit",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "split",
      hero_heading: "Coastal Elegance, Redefined",
      hero_subheading: "Mediterranean-inspired fashion and lifestyle.",
      hero_cta_label: "Shop the Coast",
    },
    navbar: "centered" as const,
    footer: "columns" as const,
    sectionPresets: [],
  },
  {
    id: "casbah",
    name: "Casbah White",
    description: "Clean white architecture with blue accents. Home goods, artisan crafts.",
    preview: { bg: "#ffffff", primary: "#1E40AF", accent: "#60A5FA", font: "Plus Jakarta Sans" },
    settings: {
      theme: "casbah",
      primary_color: "#1E40AF",
      secondary_color: "#1e293b",
      accent_color: "#60A5FA",
      background_color: "#ffffff",
      font_family: "Plus Jakarta Sans",
      button_style: "rounded",
      border_radius: "small",
      hero_layout: "centered",
      hero_heading: "Where Tradition Meets Purity",
      hero_subheading: "Artisan home goods inspired by the Casbah.",
      hero_cta_label: "Discover Art",
    },
    navbar: "hamburger" as const,
    footer: "simple" as const,
    sectionPresets: [],
  },
  {
    id: "atlas",
    name: "Atlas Cedar",
    description:
      "Forest greens and warm browns from the Atlas Mountains. Organic, wellness, nature.",
    preview: { bg: "#f0fdf4", primary: "#16A34A", accent: "#A3E635", font: "Manrope" },
    settings: {
      theme: "atlas",
      primary_color: "#16A34A",
      secondary_color: "#1a2e1a",
      accent_color: "#A3E635",
      background_color: "#f0fdf4",
      font_family: "Manrope",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "fullbleed",
      hero_heading: "Rooted in Nature",
      hero_subheading: "Organic products from the Atlas Mountains.",
      hero_cta_label: "Go Natural",
    },
    navbar: "classic" as const,
    footer: "columns" as const,
    sectionPresets: [],
  },
  {
    id: "tlemcen",
    name: "Tlemcen Ornate",
    description:
      "Rich reds and golds from Tlemcen's Islamic architecture. Luxury fashion, traditional crafts.",
    preview: { bg: "#1a1410", primary: "#B91C1C", accent: "#D4A853", font: "DM Serif Display" },
    settings: {
      theme: "tlemcen",
      primary_color: "#B91C1C",
      secondary_color: "#1c1008",
      accent_color: "#D4A853",
      background_color: "#1a1410",
      font_family: "DM Serif Display",
      button_style: "pill",
      border_radius: "medium",
      hero_layout: "fullbleed",
      hero_heading: "Heritage of Tlemcen",
      hero_subheading: "Ornate craftsmanship passed down through generations.",
      hero_cta_label: "Shop Heritage",
    },
    navbar: "centered" as const,
    footer: "branded" as const,
    sectionPresets: [],
  },
  {
    id: "constantine",
    name: "Constantine Bridge",
    description:
      "High contrast black and white with dramatic accents. Streetwear, urban, electronics.",
    preview: { bg: "#0a0a0a", primary: "#E11D48", accent: "#f8fafc", font: "Archivo Black" },
    settings: {
      theme: "constantine",
      primary_color: "#E11D48",
      secondary_color: "#0f0f0f",
      accent_color: "#f8fafc",
      background_color: "#0a0a0a",
      font_family: "Archivo Black",
      button_style: "square",
      border_radius: "none",
      hero_layout: "fullbleed",
      hero_heading: "Bridge the Gap",
      hero_subheading: "Urban essentials that defy convention.",
      hero_cta_label: "Shop Now",
    },
    navbar: "hamburger" as const,
    footer: "simple" as const,
    sectionPresets: [],
  },
  {
    id: "oran",
    name: "Oran White",
    description:
      "Crisp white with Mediterranean blue. Modern, chic, sophisticated. Fashion and beauty.",
    preview: { bg: "#f8fafc", primary: "#0284C7", accent: "#38BDF8", font: "Sora" },
    settings: {
      theme: "oran",
      primary_color: "#0284C7",
      secondary_color: "#0c4a6e",
      accent_color: "#38BDF8",
      background_color: "#f8fafc",
      font_family: "Sora",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "split",
      hero_heading: "Chic Made Simple",
      hero_subheading: "Modern Mediterranean style for the confident Algerian.",
      hero_cta_label: "Explore Style",
    },
    navbar: "classic" as const,
    footer: "columns" as const,
    sectionPresets: [],
  },
  {
    id: "ghardaia",
    name: "Ghardaia Blue",
    description: "Deep blue and white from Ghardaia's M'zab valley. Home decor, pottery, textiles.",
    preview: { bg: "#eef2ff", primary: "#1D4ED8", accent: "#93C5FD", font: "Cormorant Garamond" },
    settings: {
      theme: "ghardaia",
      primary_color: "#1D4ED8",
      secondary_color: "#1e1b4b",
      accent_color: "#93C5FD",
      background_color: "#eef2ff",
      font_family: "Cormorant Garamond",
      button_style: "pill",
      border_radius: "large",
      hero_layout: "centered",
      hero_heading: "Serenity of the M'zab",
      hero_subheading: "Handcrafted home goods from the blue city.",
      hero_cta_label: "Discover Serenity",
    },
    navbar: "centered" as const,
    footer: "branded" as const,
    sectionPresets: [],
  },
  {
    id: "kabyle",
    name: "Kabyle Earth",
    description: "Terracotta and ochre from Kabyle Berber pottery. Handcraft, pottery, textiles.",
    preview: { bg: "#fefce8", primary: "#C2410C", accent: "#F59E0B", font: "Bricolage Grotesque" },
    settings: {
      theme: "kabyle",
      primary_color: "#C2410C",
      secondary_color: "#292524",
      accent_color: "#F59E0B",
      background_color: "#fefce8",
      font_family: "Bricolage Grotesque",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "split",
      hero_heading: "Berber Roots, Modern Soul",
      hero_subheading: "Handcrafted with centuries of Kabyle tradition.",
      hero_cta_label: "Shop Handcraft",
    },
    navbar: "hamburger" as const,
    footer: "simple" as const,
    sectionPresets: [],
  },
  {
    id: "algiers",
    name: "Algiers Modern",
    description:
      "Sleek black and white with gold. Cosmopolitan, premium. Tech, fashion, accessories.",
    preview: { bg: "#fafafa", primary: "#CA8A04", accent: "#FDE68A", font: "Space Grotesk" },
    settings: {
      theme: "algiers",
      primary_color: "#CA8A04",
      secondary_color: "#0f0f0f",
      accent_color: "#FDE68A",
      background_color: "#fafafa",
      font_family: "Space Grotesk",
      button_style: "pill",
      border_radius: "small",
      hero_layout: "centered",
      hero_heading: "The Capital of Style",
      hero_subheading: "Modern essentials for cosmopolitan Algeria.",
      hero_cta_label: "Shop Premium",
    },
    navbar: "classic" as const,
    footer: "columns" as const,
    sectionPresets: [],
  },
];
