export const THEME_PRESETS = [
  {
    id: "aether",
    name: "Aether",
    description: "Light, airy, and refined. Violet accents on a warm white canvas with clean typography. Perfect for fashion, beauty, and lifestyle brands.",
    preview: { bg: "#fafaf9", primary: "#7c3aed", accent: "#f59e0b", font: "Outfit" },
    settings: {
      theme: "modern",
      primary_color: "#7c3aed",
      secondary_color: "#1e1b4b",
      accent_color: "#f59e0b",
      background_color: "#fafaf9",
      font_family: "Outfit",
      button_style: "rounded",
      border_radius: "medium",
      hero_layout: "centered",
      hero_heading: "Elevate your everyday",
      hero_subheading: "Curated pieces for the discerning eye. Where craftsmanship meets contemporary design.",
      hero_cta_label: "Explore Collection",
    },
    navbar: "classic" as const,
    footer: "columns" as const,
    sectionPresets: ["hero-centered-bento-testimonials"],
  },
  {
    id: "ember",
    name: "Ember",
    description: "Dark, bold, and energetic. Amber glows against deep charcoal. Built for streetwear, hype brands, and high-impact visuals.",
    preview: { bg: "#0c0a09", primary: "#f97316", accent: "#10b981", font: "Inter" },
    settings: {
      theme: "bold",
      primary_color: "#f97316",
      secondary_color: "#292524",
      accent_color: "#10b981",
      background_color: "#0c0a09",
      font_family: "Inter",
      button_style: "pill",
      border_radius: "medium",
      hero_layout: "fullbleed",
      hero_heading: "Bold by nature",
      hero_subheading: "Statement pieces that redefine your wardrobe. Drop 2025 is here.",
      hero_cta_label: "Shop Drop",
    },
    navbar: "hamburger" as const,
    footer: "branded" as const,
    sectionPresets: ["fullbleed-grid-cta"],
  },
  {
    id: "tide",
    name: "Tide",
    description: "Fresh, clean, and trustworthy. Teal and navy on off-white. Ideal for wellness, organic goods, and family-oriented brands.",
    preview: { bg: "#f8fafc", primary: "#0d9488", accent: "#06b6d4", font: "Jakarta" },
    settings: {
      theme: "minimal",
      primary_color: "#0d9488",
      secondary_color: "#0f172a",
      accent_color: "#06b6d4",
      background_color: "#f8fafc",
      font_family: "Jakarta",
      button_style: "rounded",
      border_radius: "small",
      hero_layout: "split",
      hero_heading: "Feel good, inside out",
      hero_subheading: "Natural wellness products crafted with intention. Your journey to balance starts here.",
      hero_cta_label: "Shop Now",
    },
    navbar: "centered" as const,
    footer: "simple" as const,
    sectionPresets: ["hero-split-grid"],
  },
];
