import { useQuery, useMutation, useQueryClient, type UseQueryResult } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import {
  listAllDropshipOrders,
  updateDropshipOrderStatus,
  listWalletTopupRequests,
  approveWalletTopup,
  rejectWalletTopup,
} from "@/lib/dropshipping/admin.functions";
import {
  listSupplyProducts,
  createSupplyProduct,
  updateSupplyProduct,
  deleteSupplyProduct,
  listSupplyOrders,
  updateSupplyOrderStatus,
  buySupplyProduct as buySupplyProductServer,
} from "@/lib/dropshipping/supply-admin.functions";

/**
 * Dropshipping marketplace hooks (TanStack Query v5).
 *
 * Reseller-side hooks query through the regular supabase client (RLS-scoped).
 * Admin hooks call server functions (useServerFn) that hold service_role.
 *
 * Generated by supabase types — see src/integrations/supabase/types.ts.
 */
import type { Database } from "@/integrations/supabase/types";

type MarketplaceProductRow = Database["public"]["Tables"]["marketplace_products"]["Row"];
type ResellerListingRow = Database["public"]["Tables"]["reseller_listings"]["Row"];
type DropshipOrderRow = Database["public"]["Tables"]["dropship_orders"]["Row"];
type ResellerWalletRow = Database["public"]["Tables"]["reseller_wallet"]["Row"];
type WalletTransactionRow = Database["public"]["Tables"]["wallet_transactions"]["Row"];
type WalletTopupRequestRow = Database["public"]["Tables"]["wallet_topup_requests"]["Row"];
type SupplyMarketplaceProductRow =
  Database["public"]["Tables"]["supply_marketplace_products"]["Row"];

// ------------------------------------------------------------
// Row types (mirrors the migration's columns exactly)
// ------------------------------------------------------------
export type MarketplaceProduct = MarketplaceProductRow;
export type ResellerListing = ResellerListingRow;
export type DropshipOrder = DropshipOrderRow;
export type WalletTopupRequest = WalletTopupRequestRow;
export type SupplyMarketplaceProduct = SupplyMarketplaceProductRow;
export type StockBuffer = Database["public"]["Tables"]["stock_buffer"]["Row"];
export type ResellerWallet = ResellerWalletRow;
export type WalletTransaction = WalletTransactionRow;

// Join shapes returned by the hooks below
export type MarketplaceProductWithJoins = MarketplaceProduct;
export type ResellerListingWithProduct = ResellerListing & {
  marketplace_product: Pick<
    MarketplaceProduct,
    | "id"
    | "name"
    | "description"
    | "images"
    | "category"
    | "platform_price"
    | "availability_status"
    | "return_rate_percent"
  > | null;
};
export type DropshipOrderWithListing = DropshipOrder & {
  reseller_listing: Pick<
    ResellerListing,
    "id" | "selling_price" | "marketplace_product_id" | "store_id"
  > | null;
};

// ------------------------------------------------------------
// Query keys (centralized so mutations can invalidate)
// ------------------------------------------------------------
export const dropshippingKeys = {
  all: ["dropshipping"] as const,
  products: (filters?: { category?: string; maxReturnRate?: number }) =>
    [...dropshippingKeys.all, "products", filters ?? {}] as const,
  myListings: (resellerId?: string) =>
    [...dropshippingKeys.all, "my-listings", resellerId ?? "anon"] as const,
  myOrders: (resellerId?: string, status?: string, storeId?: string) =>
    [
      ...dropshippingKeys.all,
      "my-orders",
      resellerId ?? "anon",
      status ?? "all",
      storeId ?? "all",
    ] as const,
  myWallet: (resellerId?: string) =>
    [...dropshippingKeys.all, "my-wallet", resellerId ?? "anon"] as const,
  myWalletTx: (resellerId?: string) =>
    [...dropshippingKeys.all, "my-wallet-tx", resellerId ?? "anon"] as const,
  myTopupRequests: (resellerId?: string) =>
    [...dropshippingKeys.all, "my-topup-requests", resellerId ?? "anon"] as const,
  adminOrders: (status?: string) =>
    [...dropshippingKeys.all, "admin-orders", status ?? "all"] as const,
  adminTopupRequests: (status?: string) =>
    [...dropshippingKeys.all, "admin-topup-requests", status ?? "all"] as const,
  supplyProducts: (filters?: { category?: string; status?: string }) =>
    [...dropshippingKeys.all, "supply-products", filters ?? {}] as const,
  adminSupplyProducts: (filters?: { category?: string; status?: string }) =>
    [...dropshippingKeys.all, "admin-supply-products", filters ?? {}] as const,
};

// ============================================================
// Reseller-facing queries
// ============================================================

/**
 * Browse the marketplace catalog.
 *
 * Filters:
 *  - category: exact match
 *  - maxReturnRate: only products with return_rate_percent <= this (0-100)
 *
 * Returns the row columns the marketplace RLS policy exposes to resellers
 * (cost_price is column-revoked server-side, so it's never returned).
 */
export function useMarketplaceProducts(filters?: {
  category?: string;
  maxReturnRate?: number;
}): UseQueryResult<MarketplaceProductWithJoins[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.products(filters),
    enabled: !!user,
    queryFn: async () => {
      let q = supabase
        .from("marketplace_products")
        .select(
          "id, name, description, images, category, supplier_name, supplier_wilaya, " +
            "platform_price, availability_status, return_rate_percent, total_orders_count, " +
            "created_at, updated_at",
        )
        .eq("availability_status", "available")
        .order("created_at", { ascending: false });
      if (filters?.category) q = q.eq("category", filters.category);
      if (typeof filters?.maxReturnRate === "number") {
        q = q.lte("return_rate_percent", filters.maxReturnRate);
      }
      const { data, error } = await q;
      if (error) {
        console.error("[useMarketplaceProducts] Query error:", error.message);
        return [] as MarketplaceProductWithJoins[];
      }
      return (data ?? []) as unknown as MarketplaceProductWithJoins[];
    },
  });
}

/** All listings the current reseller has created (joined with product). */
export function useMyResellerListings(): UseQueryResult<ResellerListingWithProduct[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.myListings(user?.id),
    enabled: !!user,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("reseller_listings")
        .select(
          "id, reseller_id, marketplace_product_id, store_id, selling_price, " +
            "is_active, total_orders, total_returns, total_profit_earned, created_at, " +
            "marketplace_product:marketplace_products!reseller_listings_marketplace_product_id_fkey" +
            "(id, name, description, images, category, platform_price, availability_status, return_rate_percent)",
        )
        .eq("reseller_id", user!.id)
        .order("created_at", { ascending: false });
      if (error) {
        console.error("[useMyResellerListings] Query error:", error.message);
        return [] as ResellerListingWithProduct[];
      }
      return (data ?? []) as unknown as ResellerListingWithProduct[];
    },
  });
}

/** Reseller's own dropship orders, optionally filtered by status and store. */
export function useMyDropshipOrders(
  status?: string,
  storeId?: string,
): UseQueryResult<DropshipOrderWithListing[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.myOrders(user?.id, status, storeId),
    enabled: !!user,
    queryFn: async () => {
      let q = supabase
        .from("dropship_orders")
        .select(
          "id, reseller_listing_id, reseller_id, client_name, client_phone, " +
            "client_wilaya, client_address, selling_price, platform_price, " +
            "reseller_profit, status, tracking_number, zr_express_id, " +
            "reseller_paid_at, shipped_at, delivered_at, refused_at, " +
            "buffer_expires_at, returned_to_reseller_at, created_at, " +
            "reseller_listing:reseller_listings!dropship_orders_reseller_listing_id_fkey" +
            "(id, selling_price, marketplace_product_id, store_id)",
        )
        .eq("reseller_id", user!.id)
        .order("created_at", { ascending: false });
      if (status) q = q.eq("status", status);
      if (storeId) q = q.eq("reseller_listing.store_id", storeId);
      const { data, error } = await q;
      if (error) {
        console.error("[useMyDropshipOrders] Query error:", error.message);
        return [] as DropshipOrderWithListing[];
      }
      return (data ?? []) as unknown as DropshipOrderWithListing[];
    },
  });
}

/** Reseller's own wallet (single row per user). */
export function useMyWallet(): UseQueryResult<ResellerWallet | null> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.myWallet(user?.id),
    enabled: !!user,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("reseller_wallet")
        .select(
          "id, reseller_id, balance, total_earned, total_spent, total_withdrawn, created_at, updated_at",
        )
        .eq("reseller_id", user!.id)
        .maybeSingle();
      if (error) {
        console.error("[useMyWallet] Query error:", error.message);
        return null;
      }
      return (data ?? null) as ResellerWallet | null;
    },
  });
}

/** Reseller's wallet ledger (newest first). */
export function useMyWalletTransactions(): UseQueryResult<WalletTransactionRow[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.myWalletTx(user?.id),
    enabled: !!user,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("wallet_transactions")
        .select(
          "id, reseller_id, type, amount, balance_after, reference_id, description, created_at",
        )
        .eq("reseller_id", user!.id)
        .order("created_at", { ascending: false })
        .limit(200);
      if (error) {
        console.error("[useMyWalletTransactions] Query error:", error.message);
        return [] as WalletTransactionRow[];
      }
      return (data ?? []) as WalletTransactionRow[];
    },
  });
}

// ============================================================
// Mutations (reseller-facing)
// ============================================================

/**
 * Update an existing reseller_listing row (selling_price and/or is_active).
 *
 * Selling price is re-validated against platform_price (DB trigger is the
 * real safety net; we pre-check for a friendlier error message).
 */
export function useUpdateMyListing() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: { listingId: string; sellingPrice?: number; isActive?: boolean }) => {
      if (!user) throw new Error("Not signed in");

      if (args.sellingPrice !== undefined) {
        if (args.sellingPrice < 0) {
          throw new Error("sellingPrice must be >= 0");
        }
        const { data: listing, error: lErr } = await supabase
          .from("reseller_listings")
          .select("marketplace_product_id")
          .eq("id", args.listingId)
          .maybeSingle();
        if (lErr) throw new Error(lErr.message);
        if (!listing) throw new Error("Listing not found");

        const { data: product, error: pErr } = await supabase
          .from("marketplace_products")
          .select("platform_price")
          .eq("id", listing.marketplace_product_id)
          .maybeSingle();
        if (pErr) throw new Error(pErr.message);
        if (args.sellingPrice < Number(product?.platform_price ?? 0)) {
          throw new Error(`sellingPrice must be >= platform_price (${product?.platform_price})`);
        }
      }

      const patch: Database["public"]["Tables"]["reseller_listings"]["Update"] = {};
      if (args.sellingPrice !== undefined) patch.selling_price = args.sellingPrice;
      if (args.isActive !== undefined) patch.is_active = args.isActive;
      if (Object.keys(patch).length === 0) {
        throw new Error("Nothing to update");
      }

      const { data, error } = await supabase
        .from("reseller_listings")
        .update(patch)
        .eq("id", args.listingId)
        .select(
          "id, reseller_id, marketplace_product_id, store_id, selling_price, is_active, total_orders, total_returns, total_profit_earned, created_at",
        )
        .single();
      if (error) throw new Error(error.message);
      return data as ResellerListing;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dropshippingKeys.myListings(user?.id) });
    },
  });
}

/**
 * Remove a product from the reseller's store (deletes the reseller_listings row).
 */
export function useRemoveMyListing() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: { listingId: string }) => {
      if (!user) throw new Error("Not signed in");
      const { error } = await supabase.from("reseller_listings").delete().eq("id", args.listingId);
      if (error) throw new Error(error.message);
      return { listingId: args.listingId };
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dropshippingKeys.myListings(user?.id) });
    },
  });
}

/**
 * Add a marketplace product to the current reseller's store.
 * Creates (or upserts) a row in reseller_listings with selling_price.
 *
 * The DB trigger trg_reseller_listings_price_check rejects selling_price
 * below the product's platform_price — we pre-check here for a friendlier
 * error message.
 */
export function useAddToMyStore() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: {
      marketplaceProductId: string;
      sellingPrice: number;
      storeId?: string | null;
    }) => {
      if (!user) throw new Error("Not signed in");
      if (args.sellingPrice < 0) throw new Error("sellingPrice must be >= 0");

      // Friendly pre-check (DB trigger is the real safety net).
      const { data: product, error: pErr } = await supabase
        .from("marketplace_products")
        .select("platform_price, availability_status")
        .eq("id", args.marketplaceProductId)
        .maybeSingle();
      if (pErr) throw new Error(pErr.message);
      if (!product) throw new Error("Marketplace product not found");
      if (product.availability_status !== "available") {
        throw new Error("This product is currently unavailable");
      }
      if (args.sellingPrice < Number(product.platform_price)) {
        throw new Error(`sellingPrice must be >= platform_price (${product.platform_price})`);
      }

      const { data, error } = await supabase
        .from("reseller_listings")
        .upsert(
          {
            reseller_id: user.id,
            marketplace_product_id: args.marketplaceProductId,
            store_id: args.storeId ?? null,
            selling_price: args.sellingPrice,
            is_active: true,
          },
          { onConflict: "reseller_id,marketplace_product_id" },
        )
        .select(
          "id, reseller_id, marketplace_product_id, store_id, selling_price, is_active, total_orders, total_returns, total_profit_earned, created_at",
        )
        .single();
      if (error) throw new Error(error.message);
      return data as ResellerListing;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dropshippingKeys.myListings(user?.id) });
    },
  });
}

/**
 * Confirm + pay for an existing pending dropship order.
 *
 * The order must already exist with status='pending_payment' (created by
 * the storefront checkout via `create_pending_dropship_order`). This hook
 * debits the wallet atomically and flips the order to 'paid_by_reseller'.
 * Insufficient balance → RPC raises P0001 with a clear message.
 */
export function useConfirmAndPayOrder() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: { orderId: string }) => {
      if (!user) throw new Error("Not signed in");
      try {
        const { error } = await supabase.rpc("confirm_and_pay_order", {
          p_order_id: args.orderId,
        });
        if (error) throw new Error(error.message);
        return args.orderId;
      } catch (e) {
        console.error("[useConfirmAndPayOrder] RPC error:", e instanceof Error ? e.message : e);
        throw e;
      }
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dropshippingKeys.myOrders(user?.id) });
      qc.invalidateQueries({ queryKey: dropshippingKeys.myWallet(user?.id) });
      qc.invalidateQueries({ queryKey: dropshippingKeys.myWalletTx(user?.id) });
      qc.invalidateQueries({ queryKey: dropshippingKeys.myListings(user?.id) });
    },
  });
}

// ============================================================
// Admin queries & mutations (server-fn backed)
// ============================================================

/** Admin: all dropship orders across the platform. */
export function useAdminDropshipOrders(status?: string): UseQueryResult<DropshipOrder[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.adminOrders(status),
    enabled: !!user,
    queryFn: async () => {
      try {
        const res = await listAllDropshipOrders({
          data: { status, limit: 100, offset: 0 },
        });
        return (res.orders ?? []) as unknown as DropshipOrder[];
      } catch (e) {
        console.error(
          "[useAdminDropshipOrders] Server fn error:",
          e instanceof Error ? e.message : e,
        );
        return [] as DropshipOrder[];
      }
    },
  });
}

/** Admin: transition a dropship order to a new status (with optional tracking). */
export function useAdminUpdateOrderStatus() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: {
      orderId: string;
      status: Database["public"]["Tables"]["dropship_orders"]["Row"]["status"];
      trackingNumber?: string;
      zrExpressId?: string;
    }) => {
      if (!user) throw new Error("Not signed in");
      const res = await updateDropshipOrderStatus({
        data: {
          order_id: args.orderId,
          status: args.status as
            | "pending_payment"
            | "paid_by_reseller"
            | "purchased_by_admin"
            | "shipped"
            | "delivered"
            | "refused"
            | "in_stock_buffer"
            | "returned_to_reseller",
          tracking_number: args.trackingNumber,
          zr_express_id: args.zrExpressId,
        },
      });
      return res.order as unknown as DropshipOrder;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "admin-orders"] });
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-orders"] });
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-wallet"] });
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-wallet-tx"] });
    },
  });
}

// ============================================================
// Wallet topup hooks (reseller + admin)
// ============================================================

/** Reseller: their own topup requests, newest first. */
export function useMyTopupRequests(): UseQueryResult<WalletTopupRequestRow[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.myTopupRequests(user?.id),
    enabled: !!user,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("wallet_topup_requests")
        .select(
          "id, reseller_id, amount, payment_reference, status, admin_note, " +
            "processed_at, processed_by, created_at",
        )
        .eq("reseller_id", user!.id)
        .order("created_at", { ascending: false });
      if (error) {
        console.error("[useMyTopupRequests] Query error:", error.message);
        return [] as unknown as WalletTopupRequestRow[];
      }
      return (data ?? []) as unknown as WalletTopupRequestRow[];
    },
  });
}

/** Reseller: ask for a wallet topup (admin must approve). */
export function useRequestWalletTopup() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: { amount: number; paymentReference: string }) => {
      if (!user) throw new Error("Not signed in");
      if (!args.paymentReference.trim()) {
        throw new Error("paymentReference is required");
      }
      if (!(args.amount > 0)) {
        throw new Error("amount must be > 0");
      }
      try {
        const { data, error } = await supabase.rpc("request_wallet_topup", {
          p_reseller_id: user.id,
          p_amount: args.amount,
          p_payment_reference: args.paymentReference,
        });
        if (error) throw new Error(error.message);
        return data as string; // request id
      } catch (e) {
        console.error("[useRequestWalletTopup] RPC error:", e instanceof Error ? e.message : e);
        throw e;
      }
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dropshippingKeys.myTopupRequests() });
      qc.invalidateQueries({ queryKey: dropshippingKeys.myWallet() });
    },
  });
}

/** Admin: list all wallet topup requests (optionally filtered by status). */
export function useAdminTopupRequests(
  status?: "pending" | "approved" | "rejected",
): UseQueryResult<WalletTopupRequestRow[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.adminTopupRequests(status),
    enabled: !!user,
    queryFn: async () => {
      try {
        const res = await listWalletTopupRequests({
          data: { status, limit: 200, offset: 0 },
        });
        const raw = res.requests as unknown;
        return raw as WalletTopupRequestRow[];
      } catch (e) {
        console.error(
          "[useAdminTopupRequests] Server fn error:",
          e instanceof Error ? e.message : e,
        );
        return [] as WalletTopupRequestRow[];
      }
    },
  });
}

/** Admin: approve a topup → credits the wallet, records ledger row. */
export function useAdminApproveTopup() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: { requestId: string; adminNote?: string; accessToken: string }) => {
      if (!user) throw new Error("Not signed in");
      const res = await approveWalletTopup({
        data: {
          request_id: args.requestId,
          admin_note: args.adminNote,
          access_token: args.accessToken,
        },
      });
      return res;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "admin-topup-requests"] });
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-wallet"] });
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-wallet-tx"] });
    },
  });
}

/** Admin: reject a topup (no wallet change). */
export function useAdminRejectTopup() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: { requestId: string; adminNote?: string; accessToken: string }) => {
      if (!user) throw new Error("Not signed in");
      const res = await rejectWalletTopup({
        data: {
          request_id: args.requestId,
          admin_note: args.adminNote,
          access_token: args.accessToken,
        },
      });
      return res;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "admin-topup-requests"] });
    },
  });
}

// ============================================================
// Supply Marketplace — Admin hooks (server-fn backed)
// ============================================================

export type SupplyOrder = Database["public"]["Tables"]["supply_orders"]["Row"];
export type UserSupplyListing = Database["public"]["Tables"]["user_supply_listings"]["Row"];

/** Admin: list all supply marketplace products. */
export function useAdminSupplyProducts(filters?: {
  category?: string;
  status?: string;
  search?: string;
}): UseQueryResult<SupplyMarketplaceProduct[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.adminSupplyProducts(filters),
    enabled: !!user,
    queryFn: async () => {
      try {
        const res = await listSupplyProducts({
          data: { ...filters, limit: 500, offset: 0 },
        });
        return (res.products ?? []) as unknown as SupplyMarketplaceProduct[];
      } catch (e) {
        console.error(
          "[useAdminSupplyProducts] Server fn error:",
          e instanceof Error ? e.message : e,
        );
        return [] as SupplyMarketplaceProduct[];
      }
    },
  });
}

/** Admin: create a supply marketplace product. */
export function useAdminCreateSupplyProduct() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: {
      name: string;
      description?: string;
      images?: string[];
      price: number;
      suggested_price: number;
      category?: string;
      stock?: number;
      supplier_name?: string;
      status?: "active" | "inactive";
    }) => {
      if (!user) throw new Error("Not signed in");
      const res = await createSupplyProduct({
        data: {
          ...args,
          created_by: user.id,
          images: args.images ?? [],
          status: args.status ?? "active",
        },
      });
      return res.product as unknown as SupplyMarketplaceProduct;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dropshippingKeys.adminSupplyProducts() });
    },
  });
}

/** Admin: update a supply marketplace product. */
export function useAdminUpdateSupplyProduct() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (args: {
      id: string;
      name?: string;
      description?: string | null;
      images?: string[];
      price?: number;
      suggested_price?: number;
      category?: string | null;
      stock?: number;
      supplier_name?: string | null;
      status?: "active" | "inactive";
    }) => {
      const res = await updateSupplyProduct({ data: args });
      return res.product as unknown as SupplyMarketplaceProduct;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dropshippingKeys.adminSupplyProducts() });
    },
  });
}

/** Admin: delete a supply marketplace product. */
export function useAdminDeleteSupplyProduct() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (args: { id: string }) => {
      const res = await deleteSupplyProduct({ data: args });
      return res;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dropshippingKeys.adminSupplyProducts() });
    },
  });
}

/** Admin: list all supply orders. */
export function useAdminSupplyOrders(
  status?: string,
): UseQueryResult<
  (SupplyOrder & {
    supply_product: Pick<SupplyMarketplaceProduct, "id" | "name" | "images" | "category"> | null;
  })[]
> {
  const { user } = useAuth();
  return useQuery({
    queryKey: [...dropshippingKeys.all, "admin-supply-orders", status ?? "all"],
    enabled: !!user,
    queryFn: async () => {
      try {
        const res = await listSupplyOrders({
          data: { status, limit: 500, offset: 0 },
        });
        return (res.orders ?? []) as unknown as (SupplyOrder & {
          supply_product: Pick<
            SupplyMarketplaceProduct,
            "id" | "name" | "images" | "category"
          > | null;
        })[];
      } catch (e) {
        console.error(
          "[useAdminSupplyOrders] Server fn error:",
          e instanceof Error ? e.message : e,
        );
        return [];
      }
    },
  });
}

/** Admin: update a supply order's status. */
export function useAdminUpdateSupplyOrderStatus() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (args: {
      orderId: string;
      status: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
    }) => {
      const res = await updateSupplyOrderStatus({
        data: { order_id: args.orderId, status: args.status },
      });
      return res.order;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "admin-supply-orders"] });
    },
  });
}

// ============================================================
// Supply Marketplace — User-side hooks
// ============================================================

/** User: browse active supply marketplace products. */
export function useSupplyProducts(filters?: {
  category?: string;
}): UseQueryResult<SupplyMarketplaceProduct[]> {
  const { user } = useAuth();
  return useQuery({
    queryKey: dropshippingKeys.supplyProducts(filters),
    enabled: !!user,
    queryFn: async () => {
      let q = supabase
        .from("supply_marketplace_products")
        .select(
          "id, name, description, images, price, suggested_price, category, " +
            "stock, supplier_name, status, created_at",
        )
        .eq("status", "active")
        .order("created_at", { ascending: false });
      if (filters?.category) q = q.eq("category", filters.category);
      const { data, error } = await q;
      if (error) {
        console.error("[useSupplyProducts] Query error:", error.message);
        return [] as SupplyMarketplaceProduct[];
      }
      return (data ?? []) as unknown as SupplyMarketplaceProduct[];
    },
  });
}

/** User: their own supply listings (products added to their store). */
export function useMySupplyListings(): UseQueryResult<
  (UserSupplyListing & {
    supply_product: Pick<
      SupplyMarketplaceProduct,
      "id" | "name" | "images" | "price" | "suggested_price" | "category" | "stock"
    > | null;
  })[]
> {
  const { user } = useAuth();
  return useQuery({
    queryKey: [...dropshippingKeys.all, "my-supply-listings", user?.id ?? "anon"],
    enabled: !!user,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("user_supply_listings")
        .select(
          "id, user_id, store_id, supply_product_id, selling_price, is_active, created_at, " +
            "supply_product:supply_marketplace_products!user_supply_listings_supply_product_id_fkey" +
            "(id, name, images, price, suggested_price, category, stock)",
        )
        .eq("user_id", user!.id)
        .order("created_at", { ascending: false });
      if (error) {
        console.error("[useMySupplyListings] Query error:", error.message);
        return [];
      }
      return (data ?? []) as unknown as (UserSupplyListing & {
        supply_product: Pick<
          SupplyMarketplaceProduct,
          "id" | "name" | "images" | "price" | "suggested_price" | "category" | "stock"
        > | null;
      })[];
    },
  });
}

/** User: add a supply product to their store. */
export function useAddSupplyToMyStore() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: {
      supplyProductId: string;
      sellingPrice: number;
      storeId?: string | null;
    }) => {
      if (!user) throw new Error("Not signed in");
      // Check if already added
      const { data: existing } = await supabase
        .from("user_supply_listings")
        .select("id")
        .eq("user_id", user.id)
        .eq("supply_product_id", args.supplyProductId)
        .maybeSingle();
      if (existing) {
        throw new Error("المنتج موجود بالفعل في متجرك");
      }
      const { data, error } = await supabase
        .from("user_supply_listings")
        .insert({
          user_id: user.id,
          supply_product_id: args.supplyProductId,
          selling_price: args.sellingPrice,
          store_id: args.storeId ?? null,
          is_active: true,
        })
        .select("id, user_id, store_id, supply_product_id, selling_price, is_active, created_at")
        .single();
      if (error) throw new Error(error.message);
      return data as UserSupplyListing;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-supply-listings", user?.id] });
    },
  });
}

/** User: remove a supply product from their store. */
export function useRemoveSupplyFromMyStore() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: { listingId: string }) => {
      if (!user) throw new Error("Not signed in");
      const { error } = await supabase
        .from("user_supply_listings")
        .delete()
        .eq("id", args.listingId);
      if (error) throw new Error(error.message);
      return { listingId: args.listingId };
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-supply-listings", user?.id] });
    },
  });
}

/** User: buy a supply product (deducts wallet, creates supply_order). */
export function useBuySupplyProduct() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (args: {
      supplyProductId: string;
      quantity?: number;
      storeId?: string | null;
    }) => {
      if (!user) throw new Error("Not signed in");
      const res = await buySupplyProductServer({
        data: {
          user_id: user.id,
          supply_product_id: args.supplyProductId,
          quantity: args.quantity ?? 1,
          store_id: args.storeId ?? undefined,
        },
      });
      return res.order as SupplyOrder;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-wallet", user?.id] });
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "my-wallet-tx", user?.id] });
      qc.invalidateQueries({ queryKey: [...dropshippingKeys.all, "admin-supply-orders"] });
      qc.invalidateQueries({ queryKey: dropshippingKeys.supplyProducts() });
    },
  });
}
