/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVoiceGeneratorRouteImport } from './routes/dashboard.voice-generator'
import { Route as DashboardUpgradeRouteImport } from './routes/dashboard.upgrade'
import { Route as DashboardThemesRouteImport } from './routes/dashboard.themes'
import { Route as DashboardThemePresetsRouteImport } from './routes/dashboard.theme-presets'
import { Route as DashboardStoreRouteImport } from './routes/dashboard.store'
import { Route as DashboardStockAlertsRouteImport } from './routes/dashboard.stock-alerts'
import { Route as DashboardShippingRouteImport } from './routes/dashboard.shipping'
import { Route as DashboardShipmentsRouteImport } from './routes/dashboard.shipments'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReturnsRouteImport } from './routes/dashboard.returns'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardLandingGeneratorRouteImport } from './routes/dashboard.landing-generator'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardDeliveryRouteImport } from './routes/dashboard.delivery'
import { Route as DashboardDatabaseRouteImport } from './routes/dashboard.database'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardCreditsRouteImport } from './routes/dashboard.credits'
import { Route as DashboardContactRouteImport } from './routes/dashboard.contact'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard.categories'
import { Route as DashboardBuilderRouteImport } from './routes/dashboard.builder'
import { Route as DashboardAppsRouteImport } from './routes/dashboard.apps'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAiAgentRouteImport } from './routes/dashboard.ai-agent'
import { Route as DashboardAboutRouteImport } from './routes/dashboard.about'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as DashboardAppsIndexRouteImport } from './routes/dashboard.apps.index'
import { Route as SSlugTrackRouteImport } from './routes/s.$slug.track'
import { Route as SSlugContactRouteImport } from './routes/s.$slug.contact'
import { Route as SSlugCheckoutRouteImport } from './routes/s.$slug.checkout'
import { Route as SSlugCartRouteImport } from './routes/s.$slug.cart'
import { Route as SSlugAboutRouteImport } from './routes/s.$slug.about'
import { Route as DashboardAppsSeoOptimizerRouteImport } from './routes/dashboard.apps.seo-optimizer'
import { Route as DashboardAppsPopupBuilderRouteImport } from './routes/dashboard.apps.popup-builder'
import { Route as DashboardAppsMultiLanguageRouteImport } from './routes/dashboard.apps.multi-language'
import { Route as DashboardAppsEmailMarketingRouteImport } from './routes/dashboard.apps.email-marketing'
import { Route as DashboardAppsDiscountGeneratorRouteImport } from './routes/dashboard.apps.discount-generator'
import { Route as DashboardAppsCurrencyConverterRouteImport } from './routes/dashboard.apps.currency-converter'
import { Route as DashboardAppsChatbotRouteImport } from './routes/dashboard.apps.chatbot'
import { Route as DashboardAppsAnalyticsRouteImport } from './routes/dashboard.apps.analytics'
import { Route as DashboardAppsAiDescriptionsRouteImport } from './routes/dashboard.apps.ai-descriptions'
import { Route as DashboardAppsAbandonedCartRouteImport } from './routes/dashboard.apps.abandoned-cart'
import { Route as DashboardAppsAppKeyRouteImport } from './routes/dashboard.apps.$appKey'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard.admin.payments'
import { Route as ApiDbTableIdRouteImport } from './routes/api.db.$tableId'
import { Route as SSlugPProductIdRouteImport } from './routes/s.$slug.p.$productId'
import { Route as SSlugCheckoutSuccessRouteImport } from './routes/s.$slug.checkout.success'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksSyncTariffsRouteImport } from './routes/api.public.hooks.sync-tariffs'
import { Route as ApiPublicHooksInstagramRouteImport } from './routes/api.public.hooks.instagram'
import { Route as ApiDbTableIdRecordIdRouteImport } from './routes/api.db.$tableId.$recordId'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoiceGeneratorRoute = DashboardVoiceGeneratorRouteImport.update({
  id: '/voice-generator',
  path: '/voice-generator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUpgradeRoute = DashboardUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardThemesRoute = DashboardThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardThemePresetsRoute = DashboardThemePresetsRouteImport.update({
  id: '/theme-presets',
  path: '/theme-presets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStoreRoute = DashboardStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStockAlertsRoute = DashboardStockAlertsRouteImport.update({
  id: '/stock-alerts',
  path: '/stock-alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShippingRoute = DashboardShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShipmentsRoute = DashboardShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReturnsRoute = DashboardReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandingGeneratorRoute =
  DashboardLandingGeneratorRouteImport.update({
    id: '/landing-generator',
    path: '/landing-generator',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliveryRoute = DashboardDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabaseRoute = DashboardDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreditsRoute = DashboardCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactRoute = DashboardContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuilderRoute = DashboardBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAgentRoute = DashboardAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/s/$slug/',
  path: '/s/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAppsIndexRoute = DashboardAppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAppsRoute,
} as any)
const SSlugTrackRoute = SSlugTrackRouteImport.update({
  id: '/s/$slug/track',
  path: '/s/$slug/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugContactRoute = SSlugContactRouteImport.update({
  id: '/s/$slug/contact',
  path: '/s/$slug/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugCheckoutRoute = SSlugCheckoutRouteImport.update({
  id: '/s/$slug/checkout',
  path: '/s/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugCartRoute = SSlugCartRouteImport.update({
  id: '/s/$slug/cart',
  path: '/s/$slug/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugAboutRoute = SSlugAboutRouteImport.update({
  id: '/s/$slug/about',
  path: '/s/$slug/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAppsSeoOptimizerRoute =
  DashboardAppsSeoOptimizerRouteImport.update({
    id: '/seo-optimizer',
    path: '/seo-optimizer',
    getParentRoute: () => DashboardAppsRoute,
  } as any)
const DashboardAppsPopupBuilderRoute =
  DashboardAppsPopupBuilderRouteImport.update({
    id: '/popup-builder',
    path: '/popup-builder',
    getParentRoute: () => DashboardAppsRoute,
  } as any)
const DashboardAppsMultiLanguageRoute =
  DashboardAppsMultiLanguageRouteImport.update({
    id: '/multi-language',
    path: '/multi-language',
    getParentRoute: () => DashboardAppsRoute,
  } as any)
const DashboardAppsEmailMarketingRoute =
  DashboardAppsEmailMarketingRouteImport.update({
    id: '/email-marketing',
    path: '/email-marketing',
    getParentRoute: () => DashboardAppsRoute,
  } as any)
const DashboardAppsDiscountGeneratorRoute =
  DashboardAppsDiscountGeneratorRouteImport.update({
    id: '/discount-generator',
    path: '/discount-generator',
    getParentRoute: () => DashboardAppsRoute,
  } as any)
const DashboardAppsCurrencyConverterRoute =
  DashboardAppsCurrencyConverterRouteImport.update({
    id: '/currency-converter',
    path: '/currency-converter',
    getParentRoute: () => DashboardAppsRoute,
  } as any)
const DashboardAppsChatbotRoute = DashboardAppsChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => DashboardAppsRoute,
} as any)
const DashboardAppsAnalyticsRoute = DashboardAppsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardAppsRoute,
} as any)
const DashboardAppsAiDescriptionsRoute =
  DashboardAppsAiDescriptionsRouteImport.update({
    id: '/ai-descriptions',
    path: '/ai-descriptions',
    getParentRoute: () => DashboardAppsRoute,
  } as any)
const DashboardAppsAbandonedCartRoute =
  DashboardAppsAbandonedCartRouteImport.update({
    id: '/abandoned-cart',
    path: '/abandoned-cart',
    getParentRoute: () => DashboardAppsRoute,
  } as any)
const DashboardAppsAppKeyRoute = DashboardAppsAppKeyRouteImport.update({
  id: '/$appKey',
  path: '/$appKey',
  getParentRoute: () => DashboardAppsRoute,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiDbTableIdRoute = ApiDbTableIdRouteImport.update({
  id: '/api/db/$tableId',
  path: '/api/db/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugPProductIdRoute = SSlugPProductIdRouteImport.update({
  id: '/s/$slug/p/$productId',
  path: '/s/$slug/p/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugCheckoutSuccessRoute = SSlugCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SSlugCheckoutRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncTariffsRoute =
  ApiPublicHooksSyncTariffsRouteImport.update({
    id: '/api/public/hooks/sync-tariffs',
    path: '/api/public/hooks/sync-tariffs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInstagramRoute = ApiPublicHooksInstagramRouteImport.update({
  id: '/api/public/hooks/instagram',
  path: '/api/public/hooks/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbTableIdRecordIdRoute = ApiDbTableIdRecordIdRouteImport.update({
  id: '/$recordId',
  path: '/$recordId',
  getParentRoute: () => ApiDbTableIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/customize': typeof CustomizeRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/themes': typeof ThemesRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/apps': typeof DashboardAppsRouteWithChildren
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contact': typeof DashboardContactRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/landing-generator': typeof DashboardLandingGeneratorRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard/shipping': typeof DashboardShippingRoute
  '/dashboard/stock-alerts': typeof DashboardStockAlertsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/theme-presets': typeof DashboardThemePresetsRoute
  '/dashboard/themes': typeof DashboardThemesRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard/voice-generator': typeof DashboardVoiceGeneratorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/db/$tableId': typeof ApiDbTableIdRouteWithChildren
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/apps/$appKey': typeof DashboardAppsAppKeyRoute
  '/dashboard/apps/abandoned-cart': typeof DashboardAppsAbandonedCartRoute
  '/dashboard/apps/ai-descriptions': typeof DashboardAppsAiDescriptionsRoute
  '/dashboard/apps/analytics': typeof DashboardAppsAnalyticsRoute
  '/dashboard/apps/chatbot': typeof DashboardAppsChatbotRoute
  '/dashboard/apps/currency-converter': typeof DashboardAppsCurrencyConverterRoute
  '/dashboard/apps/discount-generator': typeof DashboardAppsDiscountGeneratorRoute
  '/dashboard/apps/email-marketing': typeof DashboardAppsEmailMarketingRoute
  '/dashboard/apps/multi-language': typeof DashboardAppsMultiLanguageRoute
  '/dashboard/apps/popup-builder': typeof DashboardAppsPopupBuilderRoute
  '/dashboard/apps/seo-optimizer': typeof DashboardAppsSeoOptimizerRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRouteWithChildren
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/track': typeof SSlugTrackRoute
  '/dashboard/apps/': typeof DashboardAppsIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/api/db/$tableId/$recordId': typeof ApiDbTableIdRecordIdRoute
  '/api/public/hooks/instagram': typeof ApiPublicHooksInstagramRoute
  '/api/public/hooks/sync-tariffs': typeof ApiPublicHooksSyncTariffsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/s/$slug/checkout/success': typeof SSlugCheckoutSuccessRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/customize': typeof CustomizeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/themes': typeof ThemesRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contact': typeof DashboardContactRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/landing-generator': typeof DashboardLandingGeneratorRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard/shipping': typeof DashboardShippingRoute
  '/dashboard/stock-alerts': typeof DashboardStockAlertsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/theme-presets': typeof DashboardThemePresetsRoute
  '/dashboard/themes': typeof DashboardThemesRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard/voice-generator': typeof DashboardVoiceGeneratorRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/db/$tableId': typeof ApiDbTableIdRouteWithChildren
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/apps/$appKey': typeof DashboardAppsAppKeyRoute
  '/dashboard/apps/abandoned-cart': typeof DashboardAppsAbandonedCartRoute
  '/dashboard/apps/ai-descriptions': typeof DashboardAppsAiDescriptionsRoute
  '/dashboard/apps/analytics': typeof DashboardAppsAnalyticsRoute
  '/dashboard/apps/chatbot': typeof DashboardAppsChatbotRoute
  '/dashboard/apps/currency-converter': typeof DashboardAppsCurrencyConverterRoute
  '/dashboard/apps/discount-generator': typeof DashboardAppsDiscountGeneratorRoute
  '/dashboard/apps/email-marketing': typeof DashboardAppsEmailMarketingRoute
  '/dashboard/apps/multi-language': typeof DashboardAppsMultiLanguageRoute
  '/dashboard/apps/popup-builder': typeof DashboardAppsPopupBuilderRoute
  '/dashboard/apps/seo-optimizer': typeof DashboardAppsSeoOptimizerRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRouteWithChildren
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/track': typeof SSlugTrackRoute
  '/dashboard/apps': typeof DashboardAppsIndexRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/api/db/$tableId/$recordId': typeof ApiDbTableIdRecordIdRoute
  '/api/public/hooks/instagram': typeof ApiPublicHooksInstagramRoute
  '/api/public/hooks/sync-tariffs': typeof ApiPublicHooksSyncTariffsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/s/$slug/checkout/success': typeof SSlugCheckoutSuccessRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/customize': typeof CustomizeRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/themes': typeof ThemesRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/apps': typeof DashboardAppsRouteWithChildren
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contact': typeof DashboardContactRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/landing-generator': typeof DashboardLandingGeneratorRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard/shipping': typeof DashboardShippingRoute
  '/dashboard/stock-alerts': typeof DashboardStockAlertsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/theme-presets': typeof DashboardThemePresetsRoute
  '/dashboard/themes': typeof DashboardThemesRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard/voice-generator': typeof DashboardVoiceGeneratorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/db/$tableId': typeof ApiDbTableIdRouteWithChildren
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/apps/$appKey': typeof DashboardAppsAppKeyRoute
  '/dashboard/apps/abandoned-cart': typeof DashboardAppsAbandonedCartRoute
  '/dashboard/apps/ai-descriptions': typeof DashboardAppsAiDescriptionsRoute
  '/dashboard/apps/analytics': typeof DashboardAppsAnalyticsRoute
  '/dashboard/apps/chatbot': typeof DashboardAppsChatbotRoute
  '/dashboard/apps/currency-converter': typeof DashboardAppsCurrencyConverterRoute
  '/dashboard/apps/discount-generator': typeof DashboardAppsDiscountGeneratorRoute
  '/dashboard/apps/email-marketing': typeof DashboardAppsEmailMarketingRoute
  '/dashboard/apps/multi-language': typeof DashboardAppsMultiLanguageRoute
  '/dashboard/apps/popup-builder': typeof DashboardAppsPopupBuilderRoute
  '/dashboard/apps/seo-optimizer': typeof DashboardAppsSeoOptimizerRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRouteWithChildren
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/track': typeof SSlugTrackRoute
  '/dashboard/apps/': typeof DashboardAppsIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/api/db/$tableId/$recordId': typeof ApiDbTableIdRecordIdRoute
  '/api/public/hooks/instagram': typeof ApiPublicHooksInstagramRoute
  '/api/public/hooks/sync-tariffs': typeof ApiPublicHooksSyncTariffsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/s/$slug/checkout/success': typeof SSlugCheckoutSuccessRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent'
    | '/customize'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/themes'
    | '/dashboard/about'
    | '/dashboard/ai-agent'
    | '/dashboard/analytics'
    | '/dashboard/apps'
    | '/dashboard/builder'
    | '/dashboard/categories'
    | '/dashboard/contact'
    | '/dashboard/credits'
    | '/dashboard/customers'
    | '/dashboard/database'
    | '/dashboard/delivery'
    | '/dashboard/domains'
    | '/dashboard/landing-generator'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/referrals'
    | '/dashboard/returns'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/shipping'
    | '/dashboard/stock-alerts'
    | '/dashboard/store'
    | '/dashboard/theme-presets'
    | '/dashboard/themes'
    | '/dashboard/upgrade'
    | '/dashboard/voice-generator'
    | '/dashboard/'
    | '/api/db/$tableId'
    | '/dashboard/admin/payments'
    | '/dashboard/apps/$appKey'
    | '/dashboard/apps/abandoned-cart'
    | '/dashboard/apps/ai-descriptions'
    | '/dashboard/apps/analytics'
    | '/dashboard/apps/chatbot'
    | '/dashboard/apps/currency-converter'
    | '/dashboard/apps/discount-generator'
    | '/dashboard/apps/email-marketing'
    | '/dashboard/apps/multi-language'
    | '/dashboard/apps/popup-builder'
    | '/dashboard/apps/seo-optimizer'
    | '/s/$slug/about'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/contact'
    | '/s/$slug/track'
    | '/dashboard/apps/'
    | '/s/$slug/'
    | '/api/db/$tableId/$recordId'
    | '/api/public/hooks/instagram'
    | '/api/public/hooks/sync-tariffs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/s/$slug/checkout/success'
    | '/s/$slug/p/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent'
    | '/customize'
    | '/login'
    | '/signup'
    | '/themes'
    | '/dashboard/about'
    | '/dashboard/ai-agent'
    | '/dashboard/analytics'
    | '/dashboard/builder'
    | '/dashboard/categories'
    | '/dashboard/contact'
    | '/dashboard/credits'
    | '/dashboard/customers'
    | '/dashboard/database'
    | '/dashboard/delivery'
    | '/dashboard/domains'
    | '/dashboard/landing-generator'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/referrals'
    | '/dashboard/returns'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/shipping'
    | '/dashboard/stock-alerts'
    | '/dashboard/store'
    | '/dashboard/theme-presets'
    | '/dashboard/themes'
    | '/dashboard/upgrade'
    | '/dashboard/voice-generator'
    | '/dashboard'
    | '/api/db/$tableId'
    | '/dashboard/admin/payments'
    | '/dashboard/apps/$appKey'
    | '/dashboard/apps/abandoned-cart'
    | '/dashboard/apps/ai-descriptions'
    | '/dashboard/apps/analytics'
    | '/dashboard/apps/chatbot'
    | '/dashboard/apps/currency-converter'
    | '/dashboard/apps/discount-generator'
    | '/dashboard/apps/email-marketing'
    | '/dashboard/apps/multi-language'
    | '/dashboard/apps/popup-builder'
    | '/dashboard/apps/seo-optimizer'
    | '/s/$slug/about'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/contact'
    | '/s/$slug/track'
    | '/dashboard/apps'
    | '/s/$slug'
    | '/api/db/$tableId/$recordId'
    | '/api/public/hooks/instagram'
    | '/api/public/hooks/sync-tariffs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/s/$slug/checkout/success'
    | '/s/$slug/p/$productId'
  id:
    | '__root__'
    | '/'
    | '/ai-agent'
    | '/customize'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/themes'
    | '/dashboard/about'
    | '/dashboard/ai-agent'
    | '/dashboard/analytics'
    | '/dashboard/apps'
    | '/dashboard/builder'
    | '/dashboard/categories'
    | '/dashboard/contact'
    | '/dashboard/credits'
    | '/dashboard/customers'
    | '/dashboard/database'
    | '/dashboard/delivery'
    | '/dashboard/domains'
    | '/dashboard/landing-generator'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/referrals'
    | '/dashboard/returns'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/shipping'
    | '/dashboard/stock-alerts'
    | '/dashboard/store'
    | '/dashboard/theme-presets'
    | '/dashboard/themes'
    | '/dashboard/upgrade'
    | '/dashboard/voice-generator'
    | '/dashboard/'
    | '/api/db/$tableId'
    | '/dashboard/admin/payments'
    | '/dashboard/apps/$appKey'
    | '/dashboard/apps/abandoned-cart'
    | '/dashboard/apps/ai-descriptions'
    | '/dashboard/apps/analytics'
    | '/dashboard/apps/chatbot'
    | '/dashboard/apps/currency-converter'
    | '/dashboard/apps/discount-generator'
    | '/dashboard/apps/email-marketing'
    | '/dashboard/apps/multi-language'
    | '/dashboard/apps/popup-builder'
    | '/dashboard/apps/seo-optimizer'
    | '/s/$slug/about'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/contact'
    | '/s/$slug/track'
    | '/dashboard/apps/'
    | '/s/$slug/'
    | '/api/db/$tableId/$recordId'
    | '/api/public/hooks/instagram'
    | '/api/public/hooks/sync-tariffs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/s/$slug/checkout/success'
    | '/s/$slug/p/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentRoute: typeof AiAgentRoute
  CustomizeRoute: typeof CustomizeRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ThemesRoute: typeof ThemesRoute
  ApiDbTableIdRoute: typeof ApiDbTableIdRouteWithChildren
  SSlugAboutRoute: typeof SSlugAboutRoute
  SSlugCartRoute: typeof SSlugCartRoute
  SSlugCheckoutRoute: typeof SSlugCheckoutRouteWithChildren
  SSlugContactRoute: typeof SSlugContactRoute
  SSlugTrackRoute: typeof SSlugTrackRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  ApiPublicHooksInstagramRoute: typeof ApiPublicHooksInstagramRoute
  ApiPublicHooksSyncTariffsRoute: typeof ApiPublicHooksSyncTariffsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  SSlugPProductIdRoute: typeof SSlugPProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voice-generator': {
      id: '/dashboard/voice-generator'
      path: '/voice-generator'
      fullPath: '/dashboard/voice-generator'
      preLoaderRoute: typeof DashboardVoiceGeneratorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upgrade': {
      id: '/dashboard/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade'
      preLoaderRoute: typeof DashboardUpgradeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/themes': {
      id: '/dashboard/themes'
      path: '/themes'
      fullPath: '/dashboard/themes'
      preLoaderRoute: typeof DashboardThemesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/theme-presets': {
      id: '/dashboard/theme-presets'
      path: '/theme-presets'
      fullPath: '/dashboard/theme-presets'
      preLoaderRoute: typeof DashboardThemePresetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/store': {
      id: '/dashboard/store'
      path: '/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof DashboardStoreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stock-alerts': {
      id: '/dashboard/stock-alerts'
      path: '/stock-alerts'
      fullPath: '/dashboard/stock-alerts'
      preLoaderRoute: typeof DashboardStockAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shipping': {
      id: '/dashboard/shipping'
      path: '/shipping'
      fullPath: '/dashboard/shipping'
      preLoaderRoute: typeof DashboardShippingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shipments': {
      id: '/dashboard/shipments'
      path: '/shipments'
      fullPath: '/dashboard/shipments'
      preLoaderRoute: typeof DashboardShipmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/returns': {
      id: '/dashboard/returns'
      path: '/returns'
      fullPath: '/dashboard/returns'
      preLoaderRoute: typeof DashboardReturnsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/landing-generator': {
      id: '/dashboard/landing-generator'
      path: '/landing-generator'
      fullPath: '/dashboard/landing-generator'
      preLoaderRoute: typeof DashboardLandingGeneratorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/delivery': {
      id: '/dashboard/delivery'
      path: '/delivery'
      fullPath: '/dashboard/delivery'
      preLoaderRoute: typeof DashboardDeliveryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/database': {
      id: '/dashboard/database'
      path: '/database'
      fullPath: '/dashboard/database'
      preLoaderRoute: typeof DashboardDatabaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/credits': {
      id: '/dashboard/credits'
      path: '/credits'
      fullPath: '/dashboard/credits'
      preLoaderRoute: typeof DashboardCreditsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact': {
      id: '/dashboard/contact'
      path: '/contact'
      fullPath: '/dashboard/contact'
      preLoaderRoute: typeof DashboardContactRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/builder': {
      id: '/dashboard/builder'
      path: '/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof DashboardBuilderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apps': {
      id: '/dashboard/apps'
      path: '/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-agent': {
      id: '/dashboard/ai-agent'
      path: '/ai-agent'
      fullPath: '/dashboard/ai-agent'
      preLoaderRoute: typeof DashboardAiAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/about': {
      id: '/dashboard/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/s/$slug'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/apps/': {
      id: '/dashboard/apps/'
      path: '/'
      fullPath: '/dashboard/apps/'
      preLoaderRoute: typeof DashboardAppsIndexRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/s/$slug/track': {
      id: '/s/$slug/track'
      path: '/s/$slug/track'
      fullPath: '/s/$slug/track'
      preLoaderRoute: typeof SSlugTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/contact': {
      id: '/s/$slug/contact'
      path: '/s/$slug/contact'
      fullPath: '/s/$slug/contact'
      preLoaderRoute: typeof SSlugContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/checkout': {
      id: '/s/$slug/checkout'
      path: '/s/$slug/checkout'
      fullPath: '/s/$slug/checkout'
      preLoaderRoute: typeof SSlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/cart': {
      id: '/s/$slug/cart'
      path: '/s/$slug/cart'
      fullPath: '/s/$slug/cart'
      preLoaderRoute: typeof SSlugCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/about': {
      id: '/s/$slug/about'
      path: '/s/$slug/about'
      fullPath: '/s/$slug/about'
      preLoaderRoute: typeof SSlugAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/apps/seo-optimizer': {
      id: '/dashboard/apps/seo-optimizer'
      path: '/seo-optimizer'
      fullPath: '/dashboard/apps/seo-optimizer'
      preLoaderRoute: typeof DashboardAppsSeoOptimizerRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/popup-builder': {
      id: '/dashboard/apps/popup-builder'
      path: '/popup-builder'
      fullPath: '/dashboard/apps/popup-builder'
      preLoaderRoute: typeof DashboardAppsPopupBuilderRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/multi-language': {
      id: '/dashboard/apps/multi-language'
      path: '/multi-language'
      fullPath: '/dashboard/apps/multi-language'
      preLoaderRoute: typeof DashboardAppsMultiLanguageRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/email-marketing': {
      id: '/dashboard/apps/email-marketing'
      path: '/email-marketing'
      fullPath: '/dashboard/apps/email-marketing'
      preLoaderRoute: typeof DashboardAppsEmailMarketingRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/discount-generator': {
      id: '/dashboard/apps/discount-generator'
      path: '/discount-generator'
      fullPath: '/dashboard/apps/discount-generator'
      preLoaderRoute: typeof DashboardAppsDiscountGeneratorRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/currency-converter': {
      id: '/dashboard/apps/currency-converter'
      path: '/currency-converter'
      fullPath: '/dashboard/apps/currency-converter'
      preLoaderRoute: typeof DashboardAppsCurrencyConverterRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/chatbot': {
      id: '/dashboard/apps/chatbot'
      path: '/chatbot'
      fullPath: '/dashboard/apps/chatbot'
      preLoaderRoute: typeof DashboardAppsChatbotRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/analytics': {
      id: '/dashboard/apps/analytics'
      path: '/analytics'
      fullPath: '/dashboard/apps/analytics'
      preLoaderRoute: typeof DashboardAppsAnalyticsRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/ai-descriptions': {
      id: '/dashboard/apps/ai-descriptions'
      path: '/ai-descriptions'
      fullPath: '/dashboard/apps/ai-descriptions'
      preLoaderRoute: typeof DashboardAppsAiDescriptionsRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/abandoned-cart': {
      id: '/dashboard/apps/abandoned-cart'
      path: '/abandoned-cart'
      fullPath: '/dashboard/apps/abandoned-cart'
      preLoaderRoute: typeof DashboardAppsAbandonedCartRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/apps/$appKey': {
      id: '/dashboard/apps/$appKey'
      path: '/$appKey'
      fullPath: '/dashboard/apps/$appKey'
      preLoaderRoute: typeof DashboardAppsAppKeyRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/admin/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/db/$tableId': {
      id: '/api/db/$tableId'
      path: '/api/db/$tableId'
      fullPath: '/api/db/$tableId'
      preLoaderRoute: typeof ApiDbTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/p/$productId': {
      id: '/s/$slug/p/$productId'
      path: '/s/$slug/p/$productId'
      fullPath: '/s/$slug/p/$productId'
      preLoaderRoute: typeof SSlugPProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/checkout/success': {
      id: '/s/$slug/checkout/success'
      path: '/success'
      fullPath: '/s/$slug/checkout/success'
      preLoaderRoute: typeof SSlugCheckoutSuccessRouteImport
      parentRoute: typeof SSlugCheckoutRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-tariffs': {
      id: '/api/public/hooks/sync-tariffs'
      path: '/api/public/hooks/sync-tariffs'
      fullPath: '/api/public/hooks/sync-tariffs'
      preLoaderRoute: typeof ApiPublicHooksSyncTariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/instagram': {
      id: '/api/public/hooks/instagram'
      path: '/api/public/hooks/instagram'
      fullPath: '/api/public/hooks/instagram'
      preLoaderRoute: typeof ApiPublicHooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/$tableId/$recordId': {
      id: '/api/db/$tableId/$recordId'
      path: '/$recordId'
      fullPath: '/api/db/$tableId/$recordId'
      preLoaderRoute: typeof ApiDbTableIdRecordIdRouteImport
      parentRoute: typeof ApiDbTableIdRoute
    }
  }
}

interface DashboardAppsRouteChildren {
  DashboardAppsAppKeyRoute: typeof DashboardAppsAppKeyRoute
  DashboardAppsAbandonedCartRoute: typeof DashboardAppsAbandonedCartRoute
  DashboardAppsAiDescriptionsRoute: typeof DashboardAppsAiDescriptionsRoute
  DashboardAppsAnalyticsRoute: typeof DashboardAppsAnalyticsRoute
  DashboardAppsChatbotRoute: typeof DashboardAppsChatbotRoute
  DashboardAppsCurrencyConverterRoute: typeof DashboardAppsCurrencyConverterRoute
  DashboardAppsDiscountGeneratorRoute: typeof DashboardAppsDiscountGeneratorRoute
  DashboardAppsEmailMarketingRoute: typeof DashboardAppsEmailMarketingRoute
  DashboardAppsMultiLanguageRoute: typeof DashboardAppsMultiLanguageRoute
  DashboardAppsPopupBuilderRoute: typeof DashboardAppsPopupBuilderRoute
  DashboardAppsSeoOptimizerRoute: typeof DashboardAppsSeoOptimizerRoute
  DashboardAppsIndexRoute: typeof DashboardAppsIndexRoute
}

const DashboardAppsRouteChildren: DashboardAppsRouteChildren = {
  DashboardAppsAppKeyRoute: DashboardAppsAppKeyRoute,
  DashboardAppsAbandonedCartRoute: DashboardAppsAbandonedCartRoute,
  DashboardAppsAiDescriptionsRoute: DashboardAppsAiDescriptionsRoute,
  DashboardAppsAnalyticsRoute: DashboardAppsAnalyticsRoute,
  DashboardAppsChatbotRoute: DashboardAppsChatbotRoute,
  DashboardAppsCurrencyConverterRoute: DashboardAppsCurrencyConverterRoute,
  DashboardAppsDiscountGeneratorRoute: DashboardAppsDiscountGeneratorRoute,
  DashboardAppsEmailMarketingRoute: DashboardAppsEmailMarketingRoute,
  DashboardAppsMultiLanguageRoute: DashboardAppsMultiLanguageRoute,
  DashboardAppsPopupBuilderRoute: DashboardAppsPopupBuilderRoute,
  DashboardAppsSeoOptimizerRoute: DashboardAppsSeoOptimizerRoute,
  DashboardAppsIndexRoute: DashboardAppsIndexRoute,
}

const DashboardAppsRouteWithChildren = DashboardAppsRoute._addFileChildren(
  DashboardAppsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardAiAgentRoute: typeof DashboardAiAgentRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAppsRoute: typeof DashboardAppsRouteWithChildren
  DashboardBuilderRoute: typeof DashboardBuilderRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardContactRoute: typeof DashboardContactRoute
  DashboardCreditsRoute: typeof DashboardCreditsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDatabaseRoute: typeof DashboardDatabaseRoute
  DashboardDeliveryRoute: typeof DashboardDeliveryRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardLandingGeneratorRoute: typeof DashboardLandingGeneratorRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardReturnsRoute: typeof DashboardReturnsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShipmentsRoute: typeof DashboardShipmentsRoute
  DashboardShippingRoute: typeof DashboardShippingRoute
  DashboardStockAlertsRoute: typeof DashboardStockAlertsRoute
  DashboardStoreRoute: typeof DashboardStoreRoute
  DashboardThemePresetsRoute: typeof DashboardThemePresetsRoute
  DashboardThemesRoute: typeof DashboardThemesRoute
  DashboardUpgradeRoute: typeof DashboardUpgradeRoute
  DashboardVoiceGeneratorRoute: typeof DashboardVoiceGeneratorRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardAiAgentRoute: DashboardAiAgentRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAppsRoute: DashboardAppsRouteWithChildren,
  DashboardBuilderRoute: DashboardBuilderRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardContactRoute: DashboardContactRoute,
  DashboardCreditsRoute: DashboardCreditsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDatabaseRoute: DashboardDatabaseRoute,
  DashboardDeliveryRoute: DashboardDeliveryRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardLandingGeneratorRoute: DashboardLandingGeneratorRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardReturnsRoute: DashboardReturnsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShipmentsRoute: DashboardShipmentsRoute,
  DashboardShippingRoute: DashboardShippingRoute,
  DashboardStockAlertsRoute: DashboardStockAlertsRoute,
  DashboardStoreRoute: DashboardStoreRoute,
  DashboardThemePresetsRoute: DashboardThemePresetsRoute,
  DashboardThemesRoute: DashboardThemesRoute,
  DashboardUpgradeRoute: DashboardUpgradeRoute,
  DashboardVoiceGeneratorRoute: DashboardVoiceGeneratorRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiDbTableIdRouteChildren {
  ApiDbTableIdRecordIdRoute: typeof ApiDbTableIdRecordIdRoute
}

const ApiDbTableIdRouteChildren: ApiDbTableIdRouteChildren = {
  ApiDbTableIdRecordIdRoute: ApiDbTableIdRecordIdRoute,
}

const ApiDbTableIdRouteWithChildren = ApiDbTableIdRoute._addFileChildren(
  ApiDbTableIdRouteChildren,
)

interface SSlugCheckoutRouteChildren {
  SSlugCheckoutSuccessRoute: typeof SSlugCheckoutSuccessRoute
}

const SSlugCheckoutRouteChildren: SSlugCheckoutRouteChildren = {
  SSlugCheckoutSuccessRoute: SSlugCheckoutSuccessRoute,
}

const SSlugCheckoutRouteWithChildren = SSlugCheckoutRoute._addFileChildren(
  SSlugCheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentRoute: AiAgentRoute,
  CustomizeRoute: CustomizeRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ThemesRoute: ThemesRoute,
  ApiDbTableIdRoute: ApiDbTableIdRouteWithChildren,
  SSlugAboutRoute: SSlugAboutRoute,
  SSlugCartRoute: SSlugCartRoute,
  SSlugCheckoutRoute: SSlugCheckoutRouteWithChildren,
  SSlugContactRoute: SSlugContactRoute,
  SSlugTrackRoute: SSlugTrackRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  ApiPublicHooksInstagramRoute: ApiPublicHooksInstagramRoute,
  ApiPublicHooksSyncTariffsRoute: ApiPublicHooksSyncTariffsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  SSlugPProductIdRoute: SSlugPProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
