/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUpgradeRouteImport } from './routes/dashboard.upgrade'
import { Route as DashboardThemesRouteImport } from './routes/dashboard.themes'
import { Route as DashboardThemePresetsRouteImport } from './routes/dashboard.theme-presets'
import { Route as DashboardStoreRouteImport } from './routes/dashboard.store'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardContactRouteImport } from './routes/dashboard.contact'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard.categories'
import { Route as DashboardAppsRouteImport } from './routes/dashboard.apps'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAboutRouteImport } from './routes/dashboard.about'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as SSlugTrackRouteImport } from './routes/s.$slug.track'
import { Route as SSlugContactRouteImport } from './routes/s.$slug.contact'
import { Route as SSlugCheckoutRouteImport } from './routes/s.$slug.checkout'
import { Route as SSlugCartRouteImport } from './routes/s.$slug.cart'
import { Route as SSlugAboutRouteImport } from './routes/s.$slug.about'
import { Route as DashboardAppsAppKeyRouteImport } from './routes/dashboard.apps.$appKey'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard.admin.payments'
import { Route as SSlugPProductIdRouteImport } from './routes/s.$slug.p.$productId'
import { Route as SSlugCheckoutSuccessRouteImport } from './routes/s.$slug.checkout.success'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUpgradeRoute = DashboardUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardThemesRoute = DashboardThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardThemePresetsRoute = DashboardThemePresetsRouteImport.update({
  id: '/theme-presets',
  path: '/theme-presets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStoreRoute = DashboardStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactRoute = DashboardContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/s/$slug/',
  path: '/s/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugTrackRoute = SSlugTrackRouteImport.update({
  id: '/s/$slug/track',
  path: '/s/$slug/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugContactRoute = SSlugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCheckoutRoute = SSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCartRoute = SSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugAboutRoute = SSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SSlugRoute,
} as any)
const DashboardAppsAppKeyRoute = DashboardAppsAppKeyRouteImport.update({
  id: '/$appKey',
  path: '/$appKey',
  getParentRoute: () => DashboardAppsRoute,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const SSlugPProductIdRoute = SSlugPProductIdRouteImport.update({
  id: '/s/$slug/p/$productId',
  path: '/s/$slug/p/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugCheckoutSuccessRoute = SSlugCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SSlugCheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/apps': typeof DashboardAppsRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contact': typeof DashboardContactRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/theme-presets': typeof DashboardThemePresetsRoute
  '/dashboard/themes': typeof DashboardThemesRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/apps/$appKey': typeof DashboardAppsAppKeyRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRouteWithChildren
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/track': typeof SSlugTrackRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/checkout/success': typeof SSlugCheckoutSuccessRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/apps': typeof DashboardAppsRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contact': typeof DashboardContactRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/theme-presets': typeof DashboardThemePresetsRoute
  '/dashboard/themes': typeof DashboardThemesRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/apps/$appKey': typeof DashboardAppsAppKeyRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRouteWithChildren
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/track': typeof SSlugTrackRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/s/$slug/checkout/success': typeof SSlugCheckoutSuccessRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/apps': typeof DashboardAppsRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contact': typeof DashboardContactRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/theme-presets': typeof DashboardThemePresetsRoute
  '/dashboard/themes': typeof DashboardThemesRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/apps/$appKey': typeof DashboardAppsAppKeyRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRouteWithChildren
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/track': typeof SSlugTrackRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/checkout/success': typeof SSlugCheckoutSuccessRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/about'
    | '/dashboard/analytics'
    | '/dashboard/apps'
    | '/dashboard/categories'
    | '/dashboard/contact'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/store'
    | '/dashboard/theme-presets'
    | '/dashboard/themes'
    | '/dashboard/upgrade'
    | '/dashboard/'
    | '/dashboard/admin/payments'
    | '/dashboard/apps/$appKey'
    | '/s/$slug/about'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/contact'
    | '/s/$slug/track'
    | '/s/$slug/'
    | '/s/$slug/checkout/success'
    | '/s/$slug/p/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/about'
    | '/dashboard/analytics'
    | '/dashboard/apps'
    | '/dashboard/categories'
    | '/dashboard/contact'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/store'
    | '/dashboard/theme-presets'
    | '/dashboard/themes'
    | '/dashboard/upgrade'
    | '/dashboard'
    | '/dashboard/admin/payments'
    | '/dashboard/apps/$appKey'
    | '/s/$slug/about'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/contact'
    | '/s/$slug/track'
    | '/s/$slug'
    | '/s/$slug/checkout/success'
    | '/s/$slug/p/$productId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/about'
    | '/dashboard/analytics'
    | '/dashboard/apps'
    | '/dashboard/categories'
    | '/dashboard/contact'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/store'
    | '/dashboard/theme-presets'
    | '/dashboard/themes'
    | '/dashboard/upgrade'
    | '/dashboard/'
    | '/dashboard/admin/payments'
    | '/dashboard/apps/$appKey'
    | '/s/$slug/about'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/contact'
    | '/s/$slug/track'
    | '/s/$slug/'
    | '/s/$slug/checkout/success'
    | '/s/$slug/p/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SSlugTrackRoute: typeof SSlugTrackRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugPProductIdRoute: typeof SSlugPProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upgrade': {
      id: '/dashboard/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade'
      preLoaderRoute: typeof DashboardUpgradeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/themes': {
      id: '/dashboard/themes'
      path: '/themes'
      fullPath: '/dashboard/themes'
      preLoaderRoute: typeof DashboardThemesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/theme-presets': {
      id: '/dashboard/theme-presets'
      path: '/theme-presets'
      fullPath: '/dashboard/theme-presets'
      preLoaderRoute: typeof DashboardThemePresetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/store': {
      id: '/dashboard/store'
      path: '/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof DashboardStoreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact': {
      id: '/dashboard/contact'
      path: '/contact'
      fullPath: '/dashboard/contact'
      preLoaderRoute: typeof DashboardContactRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apps': {
      id: '/dashboard/apps'
      path: '/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/about': {
      id: '/dashboard/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/s/$slug'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/track': {
      id: '/s/$slug/track'
      path: '/s/$slug/track'
      fullPath: '/s/$slug/track'
      preLoaderRoute: typeof SSlugTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/contact': {
      id: '/s/$slug/contact'
      path: '/contact'
      fullPath: '/s/$slug/contact'
      preLoaderRoute: typeof SSlugContactRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/checkout': {
      id: '/s/$slug/checkout'
      path: '/checkout'
      fullPath: '/s/$slug/checkout'
      preLoaderRoute: typeof SSlugCheckoutRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/cart': {
      id: '/s/$slug/cart'
      path: '/cart'
      fullPath: '/s/$slug/cart'
      preLoaderRoute: typeof SSlugCartRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/about': {
      id: '/s/$slug/about'
      path: '/about'
      fullPath: '/s/$slug/about'
      preLoaderRoute: typeof SSlugAboutRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/dashboard/apps/$appKey': {
      id: '/dashboard/apps/$appKey'
      path: '/$appKey'
      fullPath: '/dashboard/apps/$appKey'
      preLoaderRoute: typeof DashboardAppsAppKeyRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/admin/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$slug/p/$productId': {
      id: '/s/$slug/p/$productId'
      path: '/s/$slug/p/$productId'
      fullPath: '/s/$slug/p/$productId'
      preLoaderRoute: typeof SSlugPProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/checkout/success': {
      id: '/s/$slug/checkout/success'
      path: '/success'
      fullPath: '/s/$slug/checkout/success'
      preLoaderRoute: typeof SSlugCheckoutSuccessRouteImport
      parentRoute: typeof SSlugCheckoutRoute
    }
  }
}

interface DashboardAppsRouteChildren {
  DashboardAppsAppKeyRoute: typeof DashboardAppsAppKeyRoute
}

const DashboardAppsRouteChildren: DashboardAppsRouteChildren = {
  DashboardAppsAppKeyRoute: DashboardAppsAppKeyRoute,
}

const DashboardAppsRouteWithChildren = DashboardAppsRoute._addFileChildren(
  DashboardAppsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAppsRoute: typeof DashboardAppsRouteWithChildren
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardContactRoute: typeof DashboardContactRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStoreRoute: typeof DashboardStoreRoute
  DashboardThemePresetsRoute: typeof DashboardThemePresetsRoute
  DashboardThemesRoute: typeof DashboardThemesRoute
  DashboardUpgradeRoute: typeof DashboardUpgradeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAppsRoute: DashboardAppsRouteWithChildren,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardContactRoute: DashboardContactRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStoreRoute: DashboardStoreRoute,
  DashboardThemePresetsRoute: DashboardThemePresetsRoute,
  DashboardThemesRoute: DashboardThemesRoute,
  DashboardUpgradeRoute: DashboardUpgradeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SSlugTrackRoute: SSlugTrackRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugPProductIdRoute: SSlugPProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
